name: ci-cd

on:
  push:
    branches: main

jobs:
  docker-build-push:
    name: CI-CD
    runs-on: ubuntu-latest

    env:
      WKDIR: ${{ secrets.WKDIR }}

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Checkout # checkout so that following steps can find repo files
        uses: actions/checkout@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: xiaoxihome-api
          IMAGE_TAG: latest
        run: |
          cd core
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Configure SSH
        env:
          SSH_USER: ${{ secrets.SSH_USERNAME }}
          SSH_KEY: ${{ secrets.SSH_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
        run: |
          echo "HOST=prod" >> $GITHUB_ENV
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/$HOST.key
          chmod 600 ~/.ssh/$HOST.key
          cat >>~/.ssh/config <<END
          Host prod
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/$HOST.key
            StrictHostKeyChecking no
          END

      - name: Pull docker-compose
        run: ssh $HOST "cd $WKDIR && git pull"

      - name: Remote docker login
        run: >
          ssh $HOST "
          cd $WKDIR &&
          docker login -u AWS -p $(aws ecr get-login-password --region the-region-you-are-in) ${{ steps.login-ecr.outputs.registry }}/xiaoxihome-api "

      - name: Pull
        run: ssh $HOST "cd $WKDIR && sudo docker-compose pull"

      - name: Stop
        run: ssh $HOST "cd $WKDIR && sudo docker-compose stop"

      - name: Up
        run: ssh $HOST "cd $WKDIR && sudo docker-compose up --detach"
